substitutions:
  name: "esp8266-bh1750"
  friendly_name: "ESP8266-BH1750"
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  
  name_add_mac_suffix: true
  project:
    name: esphome.project-template
    version: "1.0"

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_key

wifi:
  networks:
  - ssid: !secret wifi_ssid_0
    password: !secret wifi_password_0
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
status_led:
  pin:
    number: GPIO13
    inverted: False
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 5s
  - platform: uptime
    name: Uptime Sensor
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address


button:
  - platform: restart
    name: "Restart"